### ISSUE TITLE
How to test a website?

### ISSUE THREAD

**Issue by yugonglian** [marmelab/gremlins.js#172]
The portal for the delivery url was not found. For ex:I want to test https://www.google.com/

**Comment by HALLERPierre** [comment]
Hello @yugonglian,

In order to unleash gremlins from your browser on a website you can use the (bookmarklet)[https://marmelab.com/gremlins.js/). Just drag the link in your favorite bar and click on it to unleash them on a website.

Be aware that some websites block external scripts (like stackoverflow or github). But it should works on google.com.

I'm closing the issue as it's not a feature request or a bug.
